"use strict";

// DO NOT EDIT THIS FILE UNLESS YOU KNOW WHAT YOU ARE DOING
// If you want to change key parts of the website, go to the config.js file
// Most of the stuff you want to edit is there and it's much easier to understand


// Check if the config.js file is loaded
if (typeof GMSERVER_IP === 'undefined') {
	console.error("config.js is not loaded. Please make sure that the config.js file is loaded before main.js");
}

function launchUri(uri) {
	var parent, iframe;
	function createHiddenIframe(parent) {
		var iframe;
		if (!parent) parent = document.body;
		iframe = document.createElement('iframe');
		iframe.style.display = 'none';
		parent.appendChild(iframe);
		return iframe;
	}
	function removeHiddenIframe(parent) {
		if (!iframe) return;
		if (!parent) parent = document.body;
		parent.removeChild(iframe);
		iframe = null;
	}
	iframe = createHiddenIframe();
	iframe.contentWindow.location.href = uri;
	window.setTimeout(function () {
		removeHiddenIframe(parent);
	}, 500);
}


/* Constructing general info */
// Parameter handling
let urlParams = new URLSearchParams(window.location.search);
let ip = urlParams.get('ip');
let port = urlParams.get('port');
let pass = urlParams.get('pass');

if (!ip) ip = GMSERVER_IP;
if (!port) port = GMSERVER_PORT;
if (!port) port = "27015";
if (!pass) pass = "";

// Only if ip is provided, we can do everything else
if(ip) {
	// Steam Connect Url
	let steamconnectUrl = "steam://connect/" + ip + ":" + port;
	if (pass != "") steamconnectUrl += "/" + pass;
	// GMod Command
	let gmodcmd = "connect " + ip + ":" + port;
	if (pass != "") gmodcmd += "; password " + pass + ";";
	
	// Push Steam Connect
	if (AUTO_CONNECT) launchUri(steamconnectUrl)
}
